In [30]:
import pandas as pd

arquivo = pd.read_json(r"C:\Users\anton\Downloads\todos_os_produtos_2024-05-29T19_00_09.750649Z.json")

df_bagy = pd.DataFrame(arquivo)

In [31]:
df_bagy.columns

Index(['Sell In Kit Only', 'Active', 'Variations → Price Compare',
       'Shops → Slug', 'Stock Location', 'Meta Keywords', 'Variations → Price',
       'Brands → Name', 'Variations → Sku', 'Tags', 'Variations → Reference',
       'Categories - Category Default → Name', 'Meta Title', 'Age Group',
       'Gender', 'Ncm', 'Price', 'Billet Discount', 'Width', 'Model',
       'Sell Out Of Stock', 'Weight', 'Colors → Name', 'Meta Description',
       'ID', 'Variations → Mpn', 'Description', 'Variations → Active',
       'Additional Time Out Of Stock', 'Kit', 'Height', 'Is Gift', 'Cost',
       'Attribute Values → Name', 'Slug', 'Price Compare', 'Short Description',
       'Name', 'Depth', 'Stocks → Balance', 'Variations → External ID',
       'Variations → Gtin', 'Variations → ID', 'Kit Markup',
       'Price Out Of Stock', 'External ID', 'Relevance', 'Warranty'],
      dtype='object')

In [37]:
df_resumida = df_bagy[['Brands → Name', 'Categories - Category Default → Name', 'Price', 'Cost', 'Slug', 'Name', 'Stocks → Balance', 'External ID']]
df_resumida  = df_resumida.rename(columns={'Brands → Name': 'Marca', 'Categories - Category Default → Name': 'Categoria', 'Price': 'Preço', 'Cost': 'Custo', 'Slug': 'Link', 'Name': 'Produto', 'Stocks → Balance': 'Estoque', 'External ID': 'SKU Pai'})
ordem_colunas = ['SKU Pai', 'Produto', 'Link', 'Estoque', 'Marca', 'Categoria', 'Preço', 'Custo']
df_resumida = df_resumida[ordem_colunas]
df_resumida['Total Preço'] = df_resumida['Preço'] * df_resumida['Estoque'] 
df_resumida['Total Custo'] = df_resumida['Estoque'] * df_resumida['Custo']
df_resumida.head(5)

,SKU Pai,Produto,Link,Estoque,Marca,Categoria,Preço,Custo,Total Preço,Total Custo
0,196988,Bermuda Aeropostale D Água Masculina Logo Azul...,https://secretoutlet.bagypro.com/bermuda-aerop...,0,Aeropostale,Bermudas Aeropostale,159.99,54.62,0.00,0.0
1,196988,Bermuda Aeropostale D Água Masculina Logo Azul...,https://secretoutlet.bagypro.com/bermuda-aerop...,0,Aeropostale,Bermudas Aeropostale,159.99,54.62,0.00,0.0
2,196988,Bermuda Aeropostale D Água Masculina Logo Azul...,https://secretoutlet.bagypro.com/bermuda-aerop...,0,Aeropostale,Bermudas Aeropostale,159.99,54.62,0.00,0.0
3,196988,Bermuda Aeropostale D Água Masculina Logo Azul...,https://secretoutlet.bagypro.com/bermuda-aerop...,0,Aeropostale,Bermudas Aeropostale,159.99,54.62,0.00,0.0
4,253696,Bermuda Aeropostale D'Água Masculina Bold Logo...,https://secretoutlet.bagypro.com/bermuda-aerop...,3,Aeropostale,Bermudas Aeropostale,229.99,84.90,689.97,254.7

In [66]:
df_agrupada = df_resumida.groupby('SKU Pai').agg({
    'Produto': 'first',
    'Link': 'first',
    'Estoque': 'sum',
    'Marca': 'first',
    'Categoria': 'first',
    'Preço': 'sum',
    'Custo': 'sum',
    'Total Preço': 'sum',
    'Total Custo': 'sum'
}).reset_index()
df_agrupada = df_agrupada.sort_values(by='Estoque', ascending=False).reset_index(drop=True)
df_agrupada['Marca'].dropna()

df_agrupada

,SKU Pai,Produto,Link,Estoque,Marca,Categoria,Preço,Custo,Total Preço,Total Custo
0,204478,Camiseta Lacoste Masculina Jersey Pima Cotton ...,https://secretoutlet.bagypro.com/camiseta-laco...,3207,Lacoste,Camiseta Lacoste,2099.93,279.37,962067.93,127991.37
1,251588,Boné Lacoste Casual Side Logo Preto,https://secretoutlet.bagypro.com/bone-lacoste-...,2128,Lacoste,Bonés Lacoste,147.36,48.55,313582.08,103314.40
2,231492,Camiseta Tommy Hilfiger Masculina Essential Co...,https://secretoutlet.bagypro.com/camiseta-tomm...,2067,Tommy Hilfiger,Camisetas Tommy Hilfiger,820.98,246.12,282827.61,84788.34
3,251586,Boné Lacoste Casual Side Logo Azul Marinho,https://secretoutlet.bagypro.com/bone-lacoste-...,1904,Lacoste,Bonés Lacoste,147.36,49.65,280573.44,94533.60
4,205224,Boné Lacoste Gabardine Big Croco Preto,https://secretoutlet.bagypro.com/bone-lacoste-...,1837,Lacoste,Bonés Lacoste,147.36,50.53,270700.32,92823.61
...,...,...,...,...,...,...,...,...,...,...
17405,223517,Polo Lacoste Masculina L.12.12 Vermelho Escuro,https://secretoutlet.bagypro.com/polo-lacoste-...,0,Lacoste,Polos Lacoste,2959.92,1078.96,0.00,0.00
17406,223508,Polo Lacoste Masculina Classic Fit Mescla Caqui,https://secretoutlet.bagypro.com/polo-lacoste-...,0,Lacoste,Polos Lacoste,3119.92,1137.44,0.00,0.00
17407,233524,Polo Tommy Jeans Masculina Regular Badge Light...,https://secretoutlet.bagypro.com/polo-tommy-je...,-1,Tommy Jeans,Polos Tommy Jeans,1799.94,668.16,-299.99,-111.36
17408,240290,Cuecas Calvin Klein Brief Cotton Print Preta P...,https://secretoutlet.bagypro.com/cuecas-calvin...,-1,Calvin Klein,Cuecas Calvin Klein,679.96,289.08,-169.99,-72.27
17409,241722,Boné New Era 9Forty MLB Yankees Veranito BLK P...,https://secretoutlet.bagypro.com/bone-new-era-...,-1,New Era,Bonés New Era,199.99,82.00,-199.99,-82.00

In [71]:
def remover_marca(categoria, marca):
    if pd.isna(categoria) or pd.isna(marca):
        return categoria
    # Substituir todas as ocorrências de 'marca' em 'categoria' e remover espaços extras
    return categoria.replace(marca, '').strip()

# Aplicar a função para remover a marca da coluna Categoria
df_agrupada['Categoria'] = df_agrupada.apply(lambda row: remover_marca(row['Categoria'], row['Marca']), axis=1)

# Exibir o DataFrame resultante
df_teste = df_agrupada[['Marca', 'Categoria']]
df_teste = df_teste.groupby('Categoria').agg({
    'Marca': 'first'
}).reset_index()

df_teste

                                        Categoria              Marca
0                                                         King & Joe
1                                      Acessórios            Reserva
2                                        Bermudas            Lacoste
3                                 Bermudas Aramis              Forum
4                            Bermudas Tommy Jeans     Tommy Hilfiger
5                               Bermudas e Shorts            Reserva
6                               Blusas e Jaquetas     Tommy Hilfiger
7                     Blusas, Jaquetas e Moletons            Lacoste
8             Blusas, Jaquetas e Moletons New Era        New Balance
9   Blusas, Jaquetas e Moletons Polo Ralph Lauren    U.S. POLO ASSN.
10     Blusas, Jaquetas e Moletons Tommy Hilfiger        Tommy Jeans
11        Blusas, Jaquetas e Moletons Tommy Jeans     Tommy Hilfiger
12                                          Bonés            Lacoste
13                        Bonés Polo Ralph Lauren    U.S. POLO ASSN.
14                          Bonés U.S. Polo Assn.    U.S. POLO ASSN.
15                                       Calçados           Columbia
16                                         Calças            Lacoste
17                             Calças Tommy Jeans     Tommy Hilfiger
18                                Camisas Sociais             Aramis
19                Camisas Sociais U.S. Polo Assn.    U.S. POLO ASSN.
20                                       Camiseta            Lacoste
21                                      Camisetas     Tommy Hilfiger
22                    Camisetas Polo Ralph Lauren    U.S. POLO ASSN.
23                       Camisetas Tommy Hilfiger        Tommy Jeans
24                          Camisetas Tommy Jeans     Tommy Hilfiger
25                      Camisetas U.S. Polo Assn.    U.S. POLO ASSN.
26                        Camisetas Von der Volke      Von Der Volke
27                                      Carteiras            Lacoste
28                                       Chinelos       Calvin Klein
29                           Chinelos e Sandálias              Crocs
30                                         Cintos            Lacoste
31                                         Cuecas            Lacoste
32                            Cuecas Ralph Lauren  Polo Ralph Lauren
33                                         Marcas               None
34                                          Meias               Mash
35                               Mochilas e Malas            Reserva
36                       Mochilas e Malas Reserva         King & Joe
37                                        Pijamas       Calvin Klein
38                              Polo Ralph Lauren    U.S. POLO ASSN.
39                                          Polos            Lacoste
40                        Polos Polo Ralph Lauren    U.S. POLO ASSN.
41                              Polos Tommy Jeans     Tommy Hilfiger
42                          Polos U.S. Polo Assn.    U.S. POLO ASSN.
43                            Polos Von der Volke      Von Der Volke
44                                         Sungas       Calvin Klein
45                                          Tênis            Lacoste
46                           Tênis Tommy Hilfiger        Tommy Jeans
47                               Tênis e Calçados            Lacoste
48                                U.S. Polo Assn.    U.S. POLO ASSN.
49                                      Underwear       Calvin Klein
50                                         Óculos            Reserva

In [77]:
import pandas as pd

# Carregar o arquivo JSON
arquivo = pd.read_json(r"C:\Users\anton\Downloads\todos_os_produtos_2024-05-29T15_05_06.99827Z.json")

df_bagy = pd.DataFrame(arquivo)

df_resumida = df_bagy[['Brands → Name', 'Categories - Category Default → Name', 'Price', 'Cost', 'Slug', 'Name', 'Stocks → Balance', 'External ID']]
df_resumida = df_resumida.rename(columns={'Brands → Name': 'Marca', 'Categories - Category Default → Name': 'Categoria', 'Price': 'Preço', 'Cost': 'Custo', 'Slug': 'Link', 'Name': 'Produto', 'Stocks → Balance': 'Estoque', 'External ID': 'SKU Pai'})
ordem_colunas = ['SKU Pai', 'Produto', 'Link', 'Estoque', 'Marca', 'Categoria', 'Preço', 'Custo']
df_resumida = df_resumida[ordem_colunas]
df_resumida['Total Preço'] = df_resumida['Preço'] * df_resumida['Estoque']
df_resumida['Total Custo'] = df_resumida['Estoque'] * df_resumida['Custo']

df_agrupada = df_resumida.groupby('SKU Pai').agg({
    'Produto': 'first',
    'Link': 'first',
    'Estoque': 'sum',
    'Marca': 'first',
    'Categoria': 'first',
    'Preço': 'sum',
    'Custo': 'sum',
    'Total Preço': 'sum',
    'Total Custo': 'sum'
}).reset_index()
df_agrupada = df_agrupada.sort_values(by='Estoque', ascending=False).reset_index(drop=True)

# Lista de palavras-chave de categorias
categorias_possiveis = ['Camiseta', 'Bermuda', 'Cueca', 'Boné', 'Camisa', 'Calça', 'Jaqueta', 'Moletom', 'Blusa', 'Polo', 'Tênis', 'Sapato']

# Função para identificar a categoria com base nas palavras-chave
def identificar_categoria(categoria):
    if pd.isna(categoria):
        return categoria
    for palavra in categorias_possiveis:
        if palavra.lower() in categoria.lower():
            return palavra
    return categoria  # Retorna a categoria original se nenhuma palavra-chave for encontrada

# Aplicar a função para ajustar a coluna Categoria
df_agrupada['Categoria'] = df_agrupada['Categoria'].apply(lambda x: identificar_categoria(x))

# Exibir o DataFrame resultante
df_teste = df_agrupada[['Marca', 'Categoria']]
df_teste = df_teste.groupby('Categoria').agg({
    'Marca': 'first'
}).reset_index()
df_teste

          Categoria         Marca
0        Acessórios       Reserva
1            Aramis        Aramis
2           Bermuda       Lacoste
3              Boné       Lacoste
4             Calça       Lacoste
..              ...           ...
97    Sungas Osklen        Osklen
98   Sungas Reserva       Reserva
99            Tênis       Lacoste
100       Underwear  Calvin Klein
101  Óculos Reserva       Reserva

[102 rows x 2 columns]